name: ci
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Debug Variables
        run: |
          echo "Docker Username: ${{ vars.DOCKER_USERNAME }}"
          echo "Repository Name: ${{ github.event.repository.name }}"

      - name: Validate Docker Environment
        run: |
          docker info || exit 1

      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          load: true
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
